#
#  CodeSystems.py
#  client-py
#
#  Generated from FHIR 4.0.1-9346c8cc45
#  2020, SMART Health IT.
#
#  THIS HAS BEEN ADAPTED FROM Swift Enums WITHOUT EVER BEING IMPLEMENTED IN
#  Python, FOR DEMONSTRATION PURPOSES ONLY.
#

class DocumentRelationshipType(object):
    """ The type of relationship between documents.
    URL: http://hl7.org/fhir/document-relationship-type
    ValueSet: http://hl7.org/fhir/ValueSet/document-relationship-type
    """
    """This document logically replaces or supersedes the target document."""
    REPLACES = "replaces"
    """This document was generated by transforming the target document (e.g. format or language conversion)."""
    TRANSFORMS = "transforms"
    """This document is a signature of the target document."""
    SIGNS = "signs"
    """This document adds additional information to the target document."""
    APPENDS = "appends"
    allowed_values = ['REPLACES', 'TRANSFORMS', 'SIGNS', 'APPENDS']