#
#  CodeSystems.py
#  client-py
#
#  Generated from FHIR 4.0.1-9346c8cc45
#  2020, SMART Health IT.
#
#  THIS HAS BEEN ADAPTED FROM Swift Enums WITHOUT EVER BEING IMPLEMENTED IN
#  Python, FOR DEMONSTRATION PURPOSES ONLY.
#

class GuidePageGeneration(object):
    """ A code that indicates how the page is generated.
    URL: http://hl7.org/fhir/guide-page-generation
    ValueSet: http://hl7.org/fhir/ValueSet/guide-page-generation
    """
    # Page is proper xhtml with no templating.  Will be brought across unchanged for standard post-processing.
    HTML = "html"
    # Page is markdown with templating.  Will use the template to create a file that imports the markdown file prior
    # to post-processing.
    MARKDOWN = "markdown"
    # Page is xml with templating.  Will use the template to create a file that imports the source file and run the
    # nominated XSLT transform (see parameters) if present prior to post-processing.
    XML = "xml"
    # Page will be generated by the publication process - no source to bring across.
    GENERATED = "generated"

    allowed_values = [HTML, MARKDOWN, XML, GENERATED]