#
#  CodeSystems.py
#  client-py
#
#  Generated from FHIR 4.0.1-9346c8cc45
#  2020, SMART Health IT.
#
#  THIS HAS BEEN ADAPTED FROM Swift Enums WITHOUT EVER BEING IMPLEMENTED IN
#  Python, FOR DEMONSTRATION PURPOSES ONLY.
#

class StructureMapTargetListMode(object):
    """ If field is a list, how to manage the production.
    URL: http://hl7.org/fhir/map-target-list-mode
    ValueSet: http://hl7.org/fhir/ValueSet/map-target-list-mode
    """
    # when the target list is being assembled, the items for this rule go first. If more than one rule defines a first
    # item (for a given instance of mapping) then this is an error.
    FIRST = "first"
    # the target instance is shared with the target instances generated by another rule (up to the first common n
    # items, then create new ones).
    SHARE = "share"
    # when the target list is being assembled, the items for this rule go last. If more than one rule defines a last
    # item (for a given instance of mapping) then this is an error.
    LAST = "last"
    # re-use the first item in the list, and keep adding content to it.
    COLLATE = "collate"

    allowed_values = [FIRST, SHARE, LAST, COLLATE]